kind: MCPServer
apiVersion: api.ibm.com/v1
metadata:
  name: device-telemetry-api-server-server-jir50
  namespace: CalderSteelMCP
  version: "1.0"
  tags: []
  domain: mcp
  labels:
    origin: mcp-rest
spec:
  title: Device Telemetry API Server MCP Server
  protocolVersion: V2025_11_25
  quota:
    $ref: CalderSteelMCP:caldersteelmcp-quota-jir50:1.0
  policy-sequence:
    - $ref: CalderSteelMCP:caldersteelmcp-freeflowpolicysequence-jir50:1.0
  capabilities:
    tools:
      - $ref: CalderSteelMCP:device-telemetry-api-server-tool-jir50:1.0
